language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
sudo: required

env:
  - API_HOST=http-amqp AMQP_HOST=rabbitmq

services:
  - docker

before_install:
  - docker network create amqp-net
  - docker run -d --hostname rabbitmq --name rabbitmq -p 8080:15672 -p 5672:5672 --network=amqp-net rabbitmq:3-management
  - docker build ./e2e/producer -t rabbit-producer:latest
  - docker run --network=amqp-net --env AMQP_HOST=rabbitmq rabbit-producer:latest
  - sudo apt-get -qq update
  - sudo apt-get install -y librabbitmq-dev libboost1.48-dev libboost-chrono1.48-dev cmake git make g++
  - export CXX=g++
  - export CC=gcc
  - sudo sh ./e2e/install_amqplib.sh
  - npm install
  - cd e2e/http-tester && npm install
  - cd ../../

script:
  - sudo docker ps -a
  - node index.js
  - sleep 5s && cd e2e/http-tester && node index.js
