language: node_js
node_js: 8
sudo: required

services:
  - docker

before_install:
  - docker network create amqp-net
  - docker run -d --hostname rabbitmq --name rabbitmq -p 8080:15672 -p 5672:5672 --network=amqp-net rabbitmq:3-management
  - docker build ./e2e/producer -t rabbit-producer:latest
  - docker run --network=amqp-net --env AMQP_HOST=rabbitmq rabbit-producer:latest
  - docker build . -t amqp-http-wrapper:latest
  - docker run -d --name amqp-producer --network=amqp-net --env AMQP_HOST=rabbitmq -p 3000:3000 amqp-http-wrapper:latest
  - cd e2e/http-tester && npm install

script:
  - sleep 10s && npm start
