version: '2'
services:
  http-tester:
    build: ./e2e/http-tester
    environment:
      - API_HOST=native-amqp
      - AMQP_HOST=rabbitmq
    depends_on:
      - "native-amqp"
      - "rabbitmq"
  native-amqp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AMQP_HOST=rabbitmq
    depends_on:
      - "rabbitmq"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "8080:15672"
