version: '2'
services:
  rabbit-producer:
    build: ./e2e/producer
    environment:
      - AMQP_HOST=rabbitmq
    depends_on:
      - "rabbitmq"
  http-tester:
    build: ./e2e/http-tester
    environment:
      - API_HOST=native-amqp
    depends_on:
      - "rabbit-producer"
      - "rabbitmq"
      - "native-amqp"
  native-amqp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AMQP_HOST=rabbitmq
    depends_on:
      - "rabbit-producer"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "8080:15672"
